E/AndroidRuntime(28749): java.lang.RuntimeException: An error occured while executing doInBackground()
E/AndroidRuntime(28749):    at android.support.v4.content.ModernAsyncTask$3.done(ModernAsyncTask.java:137)
E/AndroidRuntime(28749):    at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
E/AndroidRuntime(28749):    at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
E/AndroidRuntime(28749):    at java.util.concurrent.FutureTask.run(FutureTask.java:242)
E/AndroidRuntime(28749):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime(28749):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime(28749):    at java.lang.Thread.run(Thread.java:841)