//this is an auto-generated bug report
//package name: it.reyboz.bustorino
//version: 1.8.5
//appro_time: 1
 android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database
 	at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
 	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:209)
 	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:193)
 	at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
 	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
 	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
 	at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:804)
 	at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:789)
 	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:694)
 	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:669)
 	at it.reyboz.bustorino.middleware.StopsDB.openRecursive(StopsDB.java:134)
 	at it.reyboz.bustorino.middleware.StopsDB.openIfNeeded(StopsDB.java:116)
 	at it.reyboz.bustorino.ActivityMain$asyncWgetBusStopSuggestions.tryFetcher(ActivityMain.java:434)
 	at it.reyboz.bustorino.ActivityMain$asyncWgetBusStopSuggestions.tryFetcher(ActivityMain.java:404)
 	at it.reyboz.bustorino.middleware.AsyncWget.doInBackground(AsyncWget.java:61)
 	at it.reyboz.bustorino.middleware.AsyncWget.doInBackground(AsyncWget.java:29)
 	at android.os.AsyncTask$2.call(AsyncTask.java:287)
 	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
 	at java.lang.Thread.run(Thread.java:841)
