
The application was opened and was navigated to an Anime's listing. The listing showed several available episodes. The application was then removed from the foreground by going home. Some time later the application was brought back to the foreground and one of the episodes selected. When this occurred a failure was reported. The following is the stack trace mentioned in the logs at the time:

```
W/System.err(15417): java.lang.NullPointerException: Attempt to invoke interface method 'java.util.List dulleh.akhyou.Models.AnimeProviders.AnimeProvider.fetchSources(java.lang.String)' on a null object reference
W/System.err(15417):    at dulleh.akhyou.Anime.AnimePresenter$3.call(SourceFile:302)
W/System.err(15417):    at dulleh.akhyou.Anime.AnimePresenter$3.call(SourceFile:300)
W/System.err(15417):    at rx.internal.operators.OnSubscribeDefer.call(Unknown)
W/System.err(15417):    at rx.internal.operators.OnSubscribeDefer.call(Unknown)
W/System.err(15417):    at rx.Observable.unsafeSubscribe(Unknown)
W/System.err(15417):    at rx.internal.operators.OperatorSubscribeOn$1$1.call(Unknown)
W/System.err(15417):    at rx.internal.schedulers.ScheduledAction.run(Unknown)
W/System.err(15417):    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
W/System.err(15417):    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/System.err(15417):    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
W/System.err(15417):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
W/System.err(15417):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
W/System.err(15417):    at java.lang.Thread.run(Thread.java:818)