> 06-24 13:13:45.254: E/AndroidRuntime(24303): java.lang.RuntimeException: An error occured while executing doInBackground()
> 06-24 13:13:45.254: E/AndroidRuntime(24303): at android.support.v4.a.q$3.done(Unknown Source)
> 06-24 13:13:45.254: E/AndroidRuntime(24303): at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
> 06-24 13:13:45.254: E/AndroidRuntime(24303): at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
> 06-24 13:13:45.254: E/AndroidRuntime(24303): at java.util.concurrent.FutureTask.run(FutureTask.java:242)
> 06-24 13:13:45.254: E/AndroidRuntime(24303): at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
> 06-24 13:13:45.254: E/AndroidRuntime(24303): at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
> 06-24 13:13:45.254: E/AndroidRuntime(24303): at java.lang.Thread.run(Thread.java:841)
> 06-24 13:13:45.254: E/AndroidRuntime(24303): Caused by: java.lang.NullPointerException
> 06-24 13:13:45.254: E/AndroidRuntime(24303): at org.onebusaway.android.io.request.ObaRoutesForLocationRequest$Builder.<init>(Unknown Source)
> 06-24 13:13:45.254: E/AndroidRuntime(24303): at org.onebusaway.android.ui.br.y(Unknown Source)
> 06-24 13:13:45.254: E/AndroidRuntime(24303): at org.onebusaway.android.ui.br.f(Unknown Source)
> 06-24 13:13:45.254: E/AndroidRuntime(24303): at org.onebusaway.android.ui.br.d(Unknown Source)
> 06-24 13:13:45.254: E/AndroidRuntime(24303): at android.support.v4.a.a.e(Unknown Source)
> 06-24 13:13:45.254: E/AndroidRuntime(24303): at android.support.v4.a.b.a(Unknown Source)
> 06-24 13:13:45.254: E/AndroidRuntime(24303): at android.support.v4.a.b.a(Unknown Source)
> 06-24 13:13:45.254: E/AndroidRuntime(24303): at android.support.v4.a.q$2.call(Unknown Source)
> 06-24 13:13:45.254: E/AndroidRuntime(24303): at java.util.concurrent.FutureTask.run(FutureTask.java:237)