//this is an auto-generated bug report
//package name: org.atai.TessUI
//version: 0.3.7
//appro_time: 164
 java.lang.RuntimeException: An error occured while executing doInBackground()
 	at android.os.AsyncTask$3.done(AsyncTask.java:299)
 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:352)
 	at java.util.concurrent.FutureTask.setException(FutureTask.java:219)
 	at java.util.concurrent.FutureTask.run(FutureTask.java:239)
 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
 	at java.lang.Thread.run(Thread.java:841)
 Caused by: java.lang.NoClassDefFoundError: org.json.simple.JSONValue
 	at com.memetix.mst.MicrosoftTranslatorAPI.retrieveResponse(MicrosoftTranslatorAPI.java:161)
 	at com.memetix.mst.MicrosoftTranslatorAPI.retrieveString(MicrosoftTranslatorAPI.java:199)
 	at com.memetix.mst.translate.Translate.execute(Translate.java:61)
 	at com.memetix.mst.translate.Translate.execute(Translate.java:76)
 	at org.atai.TessUI.TessUIActivity$translation_task.doInBackground(TessUIActivity.java:646)
 	at org.atai.TessUI.TessUIActivity$translation_task.doInBackground(TessUIActivity.java:639)
 	at android.os.AsyncTask$2.call(AsyncTask.java:287)
 	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
