//this is an auto-generated bug report
//package name: com.nextgis.mobile
//version: 2.4
//appro_time: 79
 java.lang.RuntimeException: Unable to start service com.nextgis.maplibui.service.TrackerService@ad452708 with Intent { cmp=com.nextgis.mobile/com.nextgis.maplibui.service.TrackerService (has extras) }: android.database.sqlite.SQLiteException: unable to open database file (code 14)
 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2721)
 	at android.app.ActivityThread.access$1900(ActivityThread.java:141)
 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1353)
 	at android.os.Handler.dispatchMessage(Handler.java:99)
 	at android.os.Looper.loop(Looper.java:137)
 	at android.app.ActivityThread.main(ActivityThread.java:5103)
 	at java.lang.reflect.Method.invokeNative(Native Method)
 	at java.lang.reflect.Method.invoke(Method.java:525)
 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
 	at dalvik.system.NativeStart.main(Native Method)
 Caused by: android.database.sqlite.SQLiteException: unable to open database file (code 14)
 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:181)
 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:137)
 	at android.content.ContentProviderProxy.insert(ContentProviderNative.java:440)
 	at android.content.ContentResolver.insert(ContentResolver.java:914)
 	at com.nextgis.maplibui.service.TrackerService.startTrack(TrackerService.java:228)
 	at com.nextgis.maplibui.service.TrackerService.onStartCommand(TrackerService.java:190)
 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2704)
