java.lang.RuntimeException: Unable to start activity ComponentInfo{org.traccar.client/org.traccar.client.MainActivity}: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
    at android.app.ActivityThread.-wrap11(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5417)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
    at org.traccar.client.MainActivity.onRequestPermissionsResult(MainActivity.java:271)
    at android.app.Activity.requestPermissions(Activity.java:3823)
    at org.traccar.client.MainActivity.startTrackingService(MainActivity.java:240)
    at org.traccar.client.MainActivity.onCreate(MainActivity.java:121)
    at android.app.Activity.performCreate(Activity.java:6251)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)