E/AndroidRuntime( 2714): java.lang.RuntimeException: An error occured while executing doInBackground()
E/AndroidRuntime( 2714):        at android.os.AsyncTask$3.done(AsyncTask.java:200)
E/AndroidRuntime( 2714):        at java.util.concurrent.FutureTask$Sync.innerSetException(FutureTask.java:274)
E/AndroidRuntime( 2714):        at java.util.concurrent.FutureTask.setException(FutureTask.java:125)
E/AndroidRuntime( 2714):        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:308)
E/AndroidRuntime( 2714):        at java.util.concurrent.FutureTask.run(FutureTask.java:138)
E/AndroidRuntime( 2714):        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1088)
E/AndroidRuntime( 2714):        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:581)
E/AndroidRuntime( 2714):        at java.lang.Thread.run(Thread.java:1027)
E/AndroidRuntime( 2714): Caused by: java.lang.NullPointerException
E/AndroidRuntime( 2714):        at net.somethingdreadful.MAL.PrefManager.<init>(PrefManager.java:17)
E/AndroidRuntime( 2714):        at net.somethingdreadful.MAL.api.MALApi.<init>(MALApi.java:27)
E/AndroidRuntime( 2714):        at net.somethingdreadful.MAL.MALManager.<init>(MALManager.java:45)
E/AndroidRuntime( 2714):        at net.somethingdreadful.MAL.ItemGridFragment$getMangaRecordsTask.doInBackground(ItemGridFragment.java:255)
E/AndroidRuntime( 2714):        at net.somethingdreadful.MAL.ItemGridFragment$getMangaRecordsTask.doInBackground(ItemGridFragment.java:1)
E/AndroidRuntime( 2714):        at android.os.AsyncTask$2.call(AsyncTask.java:185)
E/AndroidRuntime( 2714):        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:306)